# this build injects security configurations

version: "3.2"

services: 
    ## deployer runs on http://localhost:8080/cargo-jetty-deployer/
    # http://localhost:8080/
    restsimulator :
        build: .
        ports: 
          - "8080:8080"
        volumes :
          - ./container-fs/jetty/webapps/cargo-deployer/WEB-INF/web.xml:/var/lib/jetty/webapps/cargo-deployer/WEB-INF/web.xml
          - ./container-fs/jetty/webapps/cargo-deployer/WEB-INF/jetty-web.xml:/var/lib/jetty/webapps/cargo-deployer/WEB-INF/jetty-web.xml
          - ./container-fs/jetty/etc/realm.properties:/usr/local/jetty/etc/realm.properties
      


